export const armors = [
  { name: "Programmierer Brille", defense: 15 },
  { name: "Feurige Tunika", defense: 20 },
  { name: "Titanium-Schutzanzug", defense: 30 },
  { name: "Mächtige Badehose", defense: 5 },
  { name: "Mystischer Umhang der Schüchternheit", defense: 10 },
  { name: "Ritterrüstung aus Pappe", defense: 8 },
  { name: "Plüschmantel des Kuschelns", defense: 12 },
  { name: "Wolkenanzug", defense: 25 },
  { name: "Hühnerhaut-Hemd", defense: 7 },
  { name: "Alte Zeitung als Rüstung", defense: 3 },
  { name: "Glitzerndes Disco-Outfit", defense: 18 },
  { name: "Superhelden-Cape", defense: 15 },
  { name: "Unsichtbare Schutzweste", defense: 14 },
  { name: "Dosenpanzerung", defense: 9 },
  { name: "Anzug des Bänkers", defense: 11 },
  { name: "Schildkrötenpanzer", defense: 22 },
  { name: "Kettenhemd der Drachen", defense: 27 },
  { name: "Zauberhafte Robe", defense: 20 },
  { name: "Schleier des Schattens", defense: 13 },
  { name: "Steinerner Brustpanzer", defense: 17 },
  { name: "Federleichte Schutzjacke", defense: 10 },
  { name: "Rüstung des Sturms", defense: 24 },
  { name: "Lederweste des Waldläufers", defense: 12 },
  { name: "Golem-Hülle", defense: 28 },
  { name: "Flammenfeste Schutzkleidung", defense: 19 }
];
