export const weapons = [
  { name: "Paladin's Hammer", damage: 15 },
  { name: "Schwert der tausend Wahrheiten", damage: 18 },
  { name: "Flammenwerfer der Vergeltung", damage: 17 },
  { name: "Laser-Katana des Chaos", damage: 20 },
  { name: "Donnerfaust", damage: 14 },
  { name: "Schatten-Dolch", damage: 13 },
  { name: "Riesige Gummiente", damage: 5 },
  { name: "Verfluchter Löffel", damage: 6 },
  { name: "Bananen-Schleuder", damage: 8 },
  { name: "Buch der endlosen Fußnoten", damage: 10 },
  { name: "Fliegender Teppich-Bumerang", damage: 12 },
  { name: "Laute der Zerstörung", damage: 9 },
  { name: "Schmetterlingsschwert", damage: 16 },
  { name: "Käse-Kanone", damage: 7 },
  { name: "Wurstschwert des Wahnsinns", damage: 11 },
  { name: "Elektrische Zange", damage: 15 },
  { name: "Goldener Morgenstern", damage: 18 },
  { name: "Froststab des Eises", damage: 14 },
  { name: "Zauberstab des Lichts", damage: 13 },
  { name: "Stachelkeule", damage: 17 },
  { name: "Schildbrecher-Axt", damage: 19 },
  { name: "Magischer Bumerang", damage: 12 },
  { name: "Drachenbogen", damage: 14 },
  { name: "Lichtschwert der Gerechtigkeit", damage: 20 },
  { name: "Mystische Sichel", damage: 16 }
];
